// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using day2.Models;

#nullable disable

namespace day2.Migrations
{
    [DbContext(typeof(Librarybook))]
    partial class LibrarybookModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("day2.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("day2.Models.book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("books");
                });

            modelBuilder.Entity("day2.Models.lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("lab");
                });

            modelBuilder.Entity("day2.Models.labAuthor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Authorid")
                        .HasColumnType("int");

                    b.Property<int?>("labid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Authorid");

                    b.HasIndex("labid");

                    b.ToTable("labAuthors");
                });

            modelBuilder.Entity("day2.Models.book", b =>
                {
                    b.HasOne("day2.Models.Author", "Authors")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Authors");
                });

            modelBuilder.Entity("day2.Models.labAuthor", b =>
                {
                    b.HasOne("day2.Models.Author", "Author")
                        .WithMany("labAuthors")
                        .HasForeignKey("Authorid");

                    b.HasOne("day2.Models.lab", "lab")
                        .WithMany("labAuthors")
                        .HasForeignKey("labid");

                    b.Navigation("Author");

                    b.Navigation("lab");
                });

            modelBuilder.Entity("day2.Models.Author", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("labAuthors");
                });

            modelBuilder.Entity("day2.Models.lab", b =>
                {
                    b.Navigation("labAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
